sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt

cache:
    directories:
        - webpages
        - exams

script:
    - make test
