#!/usr/bin/env python

'''Autogenerated SQL commands for creating an SQL database'''

from utils import load

CLASSES, DEPARTMENTS = load('.courses.data')
SECTIONS = load('.sections.data')

TABLES = ('''
CREATE TABLE class(
    abbr char(4),
    code varchar(4),
    title tinytext,
    description text,
    level tinytext default 'undergrad',
    credits tinyint(1) default 3,
    type tinytext default 'lecture'
)''', '''
CREATE TABLE department(
    abbr char(4),
    title tinytext
)''', '''
CREATE TABLE instructor(
    name tinytext,
    email tinytext
)''', '''
CREATE TABLE semester(
    id char(6),
    startDate date,
    endDate date,
    registrationEnd date
)''', '''
CREATE TABLE location(
    uid smallint,
    building tinytext,
    room smallint
)''', '''
CREATE TABLE sections(
    CRN tinyint(5),
    abbr char(4),
    section tinytext,
    code varchar(4),
    semester char(6),
    campus tinytext default 'Columbia',
    startTime time,
    endTime time,
    days varchar(7),
    registrationStart date,
    instructor smallint,
    location smallint,
    finalExam dateTime,
    capacity tinyint,
    remaining tinyint
);''')

base = 'INSERT INTO class (abbr, code, title) VALUES ("%s", "%s", "%s");'
class_commands = '\n'.join(base % (c['abbr'], c['code'], c['title']) for c in CLASSES)

base = 'INSERT INTO department (abbr, title) VALUES ("%s", "%s");'
department_commands = '\n'.join(base % d for d in DEPARTMENTS.items())


base = 'INSERT INTO instructor (name, email) VALUES ("%s", "%s");'
instructor_commands = '\n'.join(base % (i[0], i[1])
                              for i in set((s.get('instructor', None), s.get('instructor_email', None))
                                            for s in SECTIONS))

base = '''INSERT INTO sections (CRN, abbr, section,  code, semester, campus, startTime, endTime, days, registrationStart, instructor, location, finalExam, capacity, remaining) VALUES
        ("%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s",
         "%s", "%s", "%s", "%s", "%s", "%s", "%s");'''

section_commands = '\n'.join(base % (course.get('UID', None),
                                   course.get('abbr', None), 
                                   course.get('section', None),
                                   course.get('code', None),
                                   course.get('semester', None), 
                                   course.get('campus', None),
                                   course.get('start_time', None),
                                   course.get('end_time', None), 
                                   course.get('days', None),
                                   course.get('registration_start', None),
                                   course.get('instructor', None),
                                   course.get('location', None),
                                   course.get('final_exam', None), 
                                   course.get('capacity', None), 
                                   course.get('remaining', None))
                            for course in SECTIONS)

print("%s%s%s%s%s%s%s" % ("BEGIN TRANSACTION;", ";".join(TABLES),
                        class_commands, department_commands, instructor_commands,
                        section_commands, "COMMIT;"), end='')
