#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# don't run expensive tests if nothing changed
if [ -z $(git diff-index --cached --name-only HEAD) ]; then exit 0; fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
if ! git diff-index --check --cached $against --; then exit 1; fi

# run 'make test' against the index, not against the working tree
mkdir -p test
git checkout-index -a -f --prefix test/

# cache html
mkdir -p test/grades test/sections test/exams
ln -sf -t test/grades $(realpath grades/*.pdf grades/*.xlsx)
ln -sf -t test/sections $(realpath sections/*.html.bak)
ln -sf -t test/exams $(realpath exams/*.html)
ln -sf -t test $(realpath webpages)

make -C test test || exit 1
