#!/bin/sh
# exit on error
set -e
# show commands as they are executed
set -v

[ $# -gt 0 ] && PIP_OPTS="$@"
python3 -m pip install --upgrade $PIP_OPTS setuptools wheel twine
python3 setup.py sdist bdist_wheel bdist bdist_egg
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
python3 -m pip install -i https://test.pypi.org/simple/ gradeforge
gradeforge sql query
test -n "$(gradeforge sql query 'SELECT * FROM instructor')"
